### PR TITLE
FAB-1689 check each user element for empty users

### PR DESCRIPTION
**Pull request by mcriscolo-cs**
# Checklist:
Please check you fulfill ALL of the relevant checkboxes
- [ ] Notified docs of any potential USER-facing changes
- [ ] Added short description of the change - with relevant motivation and context. 
- [ ] Branch has the ticket number in its name (along with a ticket summary)
- [ ] Commented the code, particularly in hard-to-understand areas
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Ran `npm test` and it passes
- [ ] Changes generate no new warnings

Sending the users arg to the string parser was converting it to a string so had to move to the action method body. Now that there is an array, added a filter to check for empty values.

### CODE REVIEW

**Review by clee-cs — APPROVED** [review]

**Comment by daldridge-cs** [comment]
I don't understand why this change was necessary?  My implementation used existing/documented commander.js facilities, and worked as designed when testing locally....

**Comment by daldridge-cs** [comment]
See https://github.com/CognitiveScale/cortex-cli/pull/320 as my proposed alternative.

**Review by daldridge-cs — COMMENTED** [review]
See https://github.com/CognitiveScale/cortex-cli/pull/320

**Comment by mcriscolo-cs** [comment]
Going to use Aldridge's version of the fix.

**Pull request closed without merging**
