### PR TITLE
CCF-12767: adding deprecated warnings to project and skills generate …

### PR DESCRIPTION
**Pull request by clee-cs**
…commands

# Checklist:
Please check you fulfill ALL of the relevant checkboxes
- [ ] Notified docs of any potential USER-facing changes
- [ ] Added short description of the change - with relevant motivation and context. 
- [ ] Branch has the ticket number in its name (along with a ticket summary)
- [ ] Commented the code, particularly in hard-to-understand areas
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Ran `npm test` and it passes
- [ ] Changes generate no new warnings

### CODE REVIEW

**Comment by daldridge-cs** [comment]
Version bump anywhere?

**Comment by clee-cs** [comment]
not until we merge to master

**Comment by mburpo-CS** [comment]
> @clee-cs How about cortex datasets and connections which uses generate?

@vkarumuri-cs - those should still work, I believe. We can talk about removing them, if there's an issue though?

**Comment by vkarumuri-cs** [comment]
no issues. Just checking if they have to be removed as well as part of this assignment.

**Comment by clee-cs** [comment]
@vkarumuri-cs I don't think the other generate commands needed to be changed.. the ticket only specified the project and skills generate commands.

**Pull request merged**
